### ISSUE TITLE
Use WLCG profile for IAM client in jhub

### ISSUE THREAD

**Issue by dciangot** [DODAS-TS/dodas-docker-images#14]
`FROM ghcr.io/dodas-ts/dodas-iam-client-rec:v0.0.6-pre3 as REGISTRATION` in https://github.com/DODAS-TS/dodas-docker-images/blob/master/docker/jupyter-hub/Dockerfile#L1 per registrare alla partenza un client con profilo wlcg

Il jupyterlab a quel punto dovrebbe ritirare direttamente il token con gli scope wlcg.

@MircoT  lo implementi te che hai piu il controllo?

**Comment by MircoT** [comment]
Resolved with version >= `v1.0.9-cygno`
